cache:
  enabled: true

twig:
  cache: true
  
assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true
  
errors:
  display: true
  log: true

debugger:
  enabled: false



